spring.application.name=aiPoc
spring.ai.openai.api-key=${OPEN_AI_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=qwen/qwen3-32b
# Niveau de logging (DEBUG pour plus de détails, INFO pour standard)
logging.level.root=INFO
logging.level.com.example.aiPoc=DEBUG
logging.level.org.springframework.ai=DEBUG

# Format des logs (optionnel)
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

# Fichier de logs (optionnel, pour persister les logs)
logging.file.name=logs/app.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n